# Generated by Django 4.2.4 on 2023-08-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mssalesman', '0003_alter_mssalesmen_sal_aktif'),
        ('mscustomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trpenjualan',
            fields=[
                ('jul_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jul_tanggaljual', models.DateField()),
                ('jul_sal', models.ForeignKey(db_column='jul_sal_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mssalesman.mssalesmen')),
                ('jul_cus', models.ForeignKey(db_column='jul_cus_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mscustomer.mscustomer')),
                ('jul_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('jul_tanggalbayar', models.DateField(blank=True, null=True, verbose_name='tanggal bayar')),
                ('jul_batal', models.CharField(default='N', max_length=1, verbose_name='status pembatalan')),
            ],
            options={
                'db_table': 'trpenjualan',
            },
        ),
    ]
