# Generated by Django 4.2.4 on 2023-08-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
