# Generated by Django 4.2.4 on 2023-08-24 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msproduk', '0001_initial'),
        ('trpenjualan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dtpenjualan',
            fields=[
                ('djul_id', models.AutoField(primary_key=True, serialize=False)),
                ('djul_jul', models.ForeignKey(db_column='djul_jul_id', on_delete=django.db.models.deletion.CASCADE, to='trpenjualan.trpenjualan')),
                ('djul_prd', models.ForeignKey(db_column='djul_prd_id', on_delete=django.db.models.deletion.CASCADE, to='msproduk.msproduk')),
                ('djul_qtyjual', models.FloatField(default=0)),
                ('djul_hargasatuan', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'dtpenjualan',
            },
        ),
    ]
