# Generated by Django 4.2.4 on 2023-08-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mskota', '0002_alter_mskota_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mscustomer',
            fields=[
                ('cus_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cus_nm', models.CharField(max_length=100)),
                ('cus_tanggallahir', models.DateField(blank=True, null=True)),
                ('cus_kta', models.ForeignKey(db_column='cus_kta_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mskota.mskota')),
                ('cus_aktif', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'mscustomer',
            },
        ),
    ]
