# Generated by Django 4.2.4 on 2023-08-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscustomer', '0002_rename_cus_kta_mscustomer_kta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mscustomer',
            old_name='kta_id',
            new_name='cus_kta',
        ),
    ]
