# Generated by Django 4.2.4 on 2023-08-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mskota', '0002_alter_mskota_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mssalesmen',
            fields=[
                ('sal_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('sal_nm', models.CharField(max_length=100)),
                ('sal_bekerjasejak', models.DateField(blank=True, null=True)),
                ('sal_aktif', models.CharField(default='Y', max_length=1)),
                ('sal_kta', models.ForeignKey(db_column='sal_kta_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mskota.mskota')),
            ],
            options={
                'db_table': 'mssalesmen',
            },
        ),
    ]
