# Generated by Django 4.2.4 on 2023-08-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mssalesman', '0003_alter_mssalesmen_sal_aktif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mssalesmen',
            old_name='sal_kta',
            new_name='kota',
        ),
    ]
