# Generated by Django 4.2.4 on 2023-08-25 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssalesman', '0004_rename_sal_kta_mssalesmen_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mssalesmen',
            name='sal_bekerjasejak',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mssalesmen',
            name='sal_nm',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Only alphabetic characters and spaces are allowed.', regex='^[a-zA-Z ]*$')]),
        ),
    ]
