# Generated by Django 4.2.4 on 2023-08-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mstypeproduk',
            fields=[
                ('typ_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('typ_nm', models.CharField(max_length=100)),
                ('typ_persenkomisi', models.FloatField()),
                ('typ_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('typ_aktif', models.CharField(max_length=1)),
            ],
        ),
    ]
