# Generated by Django 4.2.4 on 2023-08-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystypeproduk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstypeproduk',
            name='typ_aktif',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='mstypeproduk',
            name='typ_persenkomisi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='mstypeproduk',
            table='mstypeproduks',
        ),
    ]
