# Generated by Django 4.2.4 on 2023-08-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystypeproduk', '0002_alter_mstypeproduk_typ_aktif_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mstypeproduk',
            table='mstypeproduk',
        ),
    ]
