# Generated by Django 4.2.4 on 2023-08-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mskota',
            fields=[
                ('kta_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('kta_nm', models.CharField(max_length=100)),
                ('kta_notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
