# Generated by Django 4.2.4 on 2023-08-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mystypeproduk', '0003_alter_mstypeproduk_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msproduk',
            fields=[
                ('prd_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('prd_nm', models.CharField(max_length=100)),
                ('prd_typ', models.ForeignKey(db_column='prd_typ_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mystypeproduk.mstypeproduk')),
                ('prd_aktif', models.CharField(default='Y', max_length=1)),
                ('prd_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('prd_hargamodal', models.FloatField(blank=True, null=True)),
                ('prd_stokawal', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'msproduk',
            },
        ),
    ]
